### ISSUE TITLE
Make 1.16.5 backport use Java 11

### ISSUE THREAD

**Issue by InsaanNotFound** [matthewperiut/quarry#1]
Yes, I could switch to J16, but some mod unfortunately uses Nashorn, which was removed in J16. Its crucial for entire modpack, so I kindly request backported version of the mod with J11/8.

**Comment by matthewperiut** [comment]
Thank you @vpzomtrrfrt! This is now available here https://www.curseforge.com/minecraft/mc-mods/bc-quarry/files/3391343
